#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Get number of processors
nProc=$(foamDictionary -entry numberOfSubdomains -value $nProc system/decomposeParDict)

# Generate mesh
# gmshToFoam $meshFile
runApplication blockMesh

# Specify initial conditions
# initialConditions

runApplication solidRoeFoam

# runApplication -s components  postProcess -func components -latestTime
