#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
solver=`getApplication`

# Get number of processors
nProc=$(foamDictionary -entry numberOfSubdomains -value $nProc system/decomposeParDict)

# Generate mesh
#meshFile=$(grep '^meshFile.*;$' constant/runParameters | sed -e 's/meshFile\(.*\);/\1/')
#gmshToFoam $meshFile
runApplication blockMesh
# Specify initial conditions
runApplication $solver
# Run solver
# if [ $nProc -eq 1 ]; then
#     $solver > log.$solver &
#     tail -f log.$solver

# elif [ $nProc -gt 1 ]; then
#     runApplication decomposePar
#     runParallel $solver &
# fi

# postProcess -func 'components(sigma)'
# runApplication -s components  postProcess -func components -latestTime

# runApplication -s graphUniform  postProcess -func graphUniform -latestTime

