#!/bin/bash

clear

cd src/boundaryConditions
./compile

cd ../mathematics
./compile

cd ../models
./compile

cd ../schemes
./compile


cd ../solidRoeFoam
./compile

cd ../../utilities/initialConditions
./compile