#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
solver=`getApplication`

# Get number of processors
# nProc=$(foamDictionary -entry numberOfSubdomains -value $nProc system/decomposeParDict)

runApplication blockMesh
runApplication $solver
runApplication -s components  postProcess -func components -latestTime
runApplication -s probe  postProcess -func probe -latestTime
runApplication -s sample  postProcess -func sample -latestTime